[package]
name = "ecargo"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.82"
cargo_metadata = "0.18.1"
eframe = "0.27.2"
egui-modal = "0.3.6"
slotmap = "1.0.7"
cargo-platform = "0.1.5"

[profile.release]
panic = "abort"
strip = true
