[package]
name = "ecargo"
description = "Cargo metadata viewer using egui"
version = "0.2.0-dev"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.82"
cargo_metadata = "0.18.1"
eframe = "0.27.2"
egui-modal = "0.3.6"
egui_commonmark = "0.15.0"
slotmap = "1.0.7"
cargo-platform = "0.1.5"
open = "5.1.2"

[profile.release]
panic = "abort"
strip = true
